### ISSUE TITLE
Inactive tabs in gvim

### ISSUE THREAD

**Issue by hoodie** [rakr/vim-one#1]
Hey there,
I really like this scheme, I just noticed a little glitch.
In gvim the background and foreground color of inactive tabs are almost identical
![screenshot_20160629_123711](https://cloud.githubusercontent.com/assets/260370/16449262/b3375e72-3df6-11e6-9c05-cf05d404bbbf.png)

cheers

**Comment by rakr** [comment]
Thanks @hoodie
This should fix the glitch.

**Comment by hoodie** [comment]
it did, thanks
