### ISSUE TITLE
End of line listcars are rendered bold

### ISSUE THREAD

**Issue by rumpelsepp** [rakr/vim-one#16]
![screenshot-2016-11-10-10 31 52](https://cloud.githubusercontent.com/assets/1961699/20171434/e93337c8-a730-11e6-839e-7cdba93d90a0.png)

**Comment by rakr** [comment]
@rumpelsepp 
This last commit should fix the problem: d221f925448eadbb9552e7e5eee2557b77b7eab1
Please give it a try.

**Comment by rumpelsepp** [comment]
Sry for the delay. It works! Thanks.
