### ISSUE TITLE
Support iterm2 color scheme

### ISSUE THREAD

**Issue by bubuzzz** [rakr/vim-one#18]
Thank you very much for the color scheme. I would say this is the best one for javascript syntax highlight. Is there any chance to make a support for iterm2 color scheme ?

**Comment by rakr** [comment]
Hi @bubuzzz, thanks.

I will not maintain my own One iTerm2 colorscheme, I'm actually using this one: https://github.com/nathanbuchar/atom-one-dark-terminal

In the scheme folder you will find the dark and light flavours.
