### ISSUE TITLE
Vim inside of tmux is broken VIM 8.0

### ISSUE THREAD

**Issue by carlweis** [rakr/vim-one#19]
I've been trying to get vim to work inside of tmux, with this color scheme, with no luck. Can you please let me know why this doesn't work, or how I can get it to work on OSX?

Can't use this if it won't allow me to use vim inside of tmux. Not sure that I want to switch to NeoVim yet. Please let me know if this is possible to get working.

set t_8b=^[[48;2;%lu;%lu;%lum
set t_8f=^[[38;2;%lu;%lu;%lum

Thank You.

**Comment by rakr** [comment]
Hi @carlweis, the most honest answer is that I don't know, I've made the switch to Neovim and did not test this colorscheme with Vim 8.
Searching briefly on Google, it seems that it is a more global problem that Vim has: https://github.com/vim/vim/issues/993

**Comment by carlweis** [comment]
@rakr thank you for that link. I'll keep an eye on this and in the meantime, see about switching to neovim.
