### ISSUE TITLE
How to set it to 'dark'

### ISSUE THREAD

**Issue by kaiyulee** [rakr/vim-one#2]
After I `PluginInstall`, it gives me the light one.

----
iTerm2 on Mac

**Comment by rakr** [comment]
In your `.vimrc` you need to set the background to either `dark` or `light`.
You can do than on the fly also by typing the following command `:set background=dark` or `:set background=light`.
The colorscheme will than adapt automatically.

**Comment by rakr** [comment]
Updated the documentation accordingly 4b9cd69ca0263707399d5b8ce2be1ea5fc355669

**Comment by kaiyulee** [comment]
you can close it.
