### ISSUE TITLE
Cyan defined twice in light background

### ISSUE THREAD

**Issue by mnacamura** [rakr/vim-one#20]
Hi. Thanks for developing this nice color scheme!

I just looked at the source code and found that, in `colors/one.vim`, cyan (`s:hue_1`) is defined twice (`#0184bc` and then `#0083be`) at lines 269-270.
I guess `#0184bc` is the original definition of one light, but `#0184bc` is overwritten by `#0083be`.
These two colors are too close to distinguish from one another with my eyes, so it actually does not matter.  
However, is there any reason to do that or is it just a bug?

**Comment by rakr** [comment]
Thanks for pointing this out, I reverted to the original color
