### ISSUE TITLE
Highlighted text on search

### ISSUE THREAD

**Issue by DenniJensen** [rakr/vim-one#22]
Hi @rakr,

if I am searching for a word, the suggested text is not highlighted well.
In the example I am search for the word `File`.

![image](https://cloud.githubusercontent.com/assets/3010752/21017759/b8ca1aca-bd6a-11e6-83d2-8cf7df7483ac.png)

![image](https://cloud.githubusercontent.com/assets/3010752/21017777/d2dcd0f6-bd6a-11e6-8d9e-e44c43b856df.png)

If you complete the search with CR I get a nice highlight.

![image](https://cloud.githubusercontent.com/assets/3010752/21017824/f52d5392-bd6a-11e6-8c26-0b230de7d13f.png)

![image](https://cloud.githubusercontent.com/assets/3010752/21017804/e9d956c6-bd6a-11e6-8876-942afb5f3870.png)

**Comment by rakr** [comment]
Thanks @DenniJensen , can you please have a look at the last commit?

**Comment by DenniJensen** [comment]
@rakr thx, this LGTM!
