### ISSUE TITLE
Credit for 24-bit color snippet in README.md

### ISSUE THREAD

**Issue by joshdick** [rakr/vim-one#24]
You have borrowed the [True Color Support](https://github.com/rakr/vim-one#true-color-support) section of your README.md from the [README.md I wrote for my own onedark.vim](https://github.com/joshdick/onedark.vim/blame/master/README.md#L15-L31), and while that doesn't violate my theme's license, I'd appreciate being credited in your contributors section!

**Comment by rakr** [comment]
Hi Josh,

First of all thanks for your feedback I was wondering who wrote this piece of code first, so now I know it is you, I mentioned you directly in the piece of code in question.
Contribution section is for people who actually contributed to this colorscheme.

Again, thanks for you feedback, but on a personal level I'm finding the written tone of your comment a little bit aggressive. I would suggest using a greeting at the very beginning and avoid using exclamation marks.

Thanks again for your comment and have a great day/year.

**Comment by joshdick** [comment]
No aggression was meant. I tried to keep it short, and sometimes using full stops (periods) reads MORE aggressively which is why I tried to keep things light with exclamation marks. My apologies that it didn't read that way.

Out of curiosity, where did you find the snippet if not in my README?

Thanks for the credit and have a happy and safe new year.
