### ISSUE TITLE
Dark theme doesn't work

### ISSUE THREAD

**Issue by joeytall** [rakr/vim-one#27]
![screen shot 2017-01-17 at 3 01 57 pm](https://cloud.githubusercontent.com/assets/2639004/22043741/f1c2e8fa-dcc5-11e6-817d-b9a24e59cdf3.png)
set background=dark
before colorscheme one

doesn't work, please help.
Really want to use this atom dark theme.
Please help.

**Comment by rakr** [comment]
Hi Joey,

If you put the colorscheme line before setting the background this would work.
