### ISSUE TITLE
Cursor line number background

### ISSUE THREAD

**Issue by andrepolischuk** [rakr/vim-one#28]
@rakr what do you think about set same backgrounds for cursor line and cursor line number?

<img width="374" alt="screen shot 2017-01-19 at 17 29 17" src="https://cloud.githubusercontent.com/assets/8956796/22110468/db875500-de6c-11e6-8671-eee8d1f28bdd.png">

**Comment by rakr** [comment]
Very good idea, thanks for pointing this out.

**Comment by andrepolischuk** [comment]
Your commit set cursor line background to all line numbers (`LineNr`)

<img width="177" alt="screen shot 2017-01-23 at 12 07 27" src="https://cloud.githubusercontent.com/assets/8956796/22197780/93bab50a-e164-11e6-9c52-54560d310833.png">

But I mean set background to cursor line number only (`CursorLineNr`). Look at the screenshot in [first comment](https://github.com/rakr/vim-one/issues/28#issue-201875798). Did you do this intentionally?

**Comment by IngoHeimbach** [comment]
The color changes to `LineNr` lead to a wrong background color of vim-gitgutter signs:
![one](https://cloud.githubusercontent.com/assets/1449087/22219261/66fee680-e1aa-11e6-8717-6bf2c02fc2ab.png)
vim-one links `GitGutterAdd` to `SignifySignAdd` which does not have a defined background color. Therefore the default background color is used for gitgutter signs.

**Comment by rakr** [comment]
Last update solves these two issues.

<img width="1042" alt="__w_v_vim-one_and___w_v_vim-one_and___w_v_vim-one" src="https://cloud.githubusercontent.com/assets/110558/22229477/09a7d2da-e22c-11e6-9b86-39ee32d501e0.png">

Now that the colorscheme is stable enough I'm now thinking about enabling some settings to allow user to tweak **one** to better suit their needs. I'm currently thinking about:
- LineNr
- Pmenu

if you have other ideas, feel free to open an issue.

**Comment by andrepolischuk** [comment]
@rakr thanks, my issue was fixed by last update.
