### ISSUE TITLE
It looks not as nice as the demo

### ISSUE THREAD

**Issue by kaiyulee** [rakr/vim-one#3]
look:

![iTerm2 or terminal on Mac ](http://o9m8gqxa3.bkt.clouddn.com/scone.png)

screenshot: http://o9m8gqxa3.bkt.clouddn.com/scone.png

**Comment by rakr** [comment]
Would you mind providing the following information:

* Terminal you are using and the version
* Vim or NeoVim and the version
* Are you using tmux?

**Comment by rakr** [comment]
Actually, i think I know the reason. Italic is not supported by your terminal. Will post a fix soon that would require a configuration setting.

**Comment by rakr** [comment]
@kaiyulee This update should fix your problem. Please make sure to have the following lines in your `~/.vimrc`

```vim
set background=dark
set g:one_allow_italics=1
colorscheme one
```

**Comment by kaiyulee** [comment]
iTerm2 Build 3.0.1 + vim 7.4.1345, iTerm2 has the tmux integration.

And still has the `clear & beautiful` problem.

It seems like not the plugin's problem. I had tried the material colorscheme mounthes before, It also has the display issue - it not as clear & beautiful as yours, but both the material and the one display well with MacVim. So the key maybe is the vim.

**Comment by rakr** [comment]
Sorry to hear that, to support True Colors in Terminal you would need

- [iTerm2 (nightly build) that you can find here](https://www.iterm2.com/downloads/nightly/#/section/home)
- Neovim > 0.1.3 or Vim > patch 7.4.1799
- Tmux 2.2 seems to support True Colors in terminal

**Comment by kepbod** [comment]
It only works for vim, but not neovim.
My information:
* Iterm2 Build 3.0.10
* Vim 8.0
* Neovim 0.1.5

**Comment by rakr** [comment]
@kepbod, Sorry but I can't help you fix this issue on Neovim if you don't provide more information, your `~/.vimrc` or `/.config/nvim/init.vim` would be a great start.
also don't forget that you must set `termguicolors` for this to work.

**Comment by kepbod** [comment]
Sorry that I forgot to attach my configuration.
My ~/.config/nvim/init.vim is https://github.com/kepbod/ivim/blob/master/vimrc_nvim, and I set iterm using https://gist.github.com/kepbod/2ea79ee2ada4c22591dc043c1ed4364c. 
Thanks a lot for your helps.

**Comment by rakr** [comment]
try removing the `set t_Co` line

**Comment by kepbod** [comment]
It did not work after I removed the `set t_Co` line.

**Comment by kepbod** [comment]
I fixed it by add below snippers in `.vimrc` according to https://www.reddit.com/r/vim/comments/24g8r8/italics_in_terminal_vim_and_tmux/?st=iux2r3zl&sh=87e1d8bf.
```
set t_ZH=^[[3m
set t_ZR=^[[23m
```

But I doesn't know why.

**Comment by b-fuze** [comment]
If kepbod's snippet above doesn't work for you like it didn't for me, then it's likely because it requires actually typing the Esc character—which won't look as nice in other editors or display properly in a browser. A nicer way that looks the same across editors and in a browser is:
```vim
let &t_ZH = "\<Esc>[3m"
let &t_ZR = "\<Esc>[23m"
```
