### ISSUE TITLE
Same background on menu for suggestions

### ISSUE THREAD

**Issue by DenniJensen** [rakr/vim-one#32]
Hi,

it is hard in vim-one to see the menu for the autocompletion suggestions.
**Dark**
![image](https://cloud.githubusercontent.com/assets/3010752/22697410/a664749a-ed51-11e6-9ae6-e9b310231450.png)

**Light**
![image](https://cloud.githubusercontent.com/assets/3010752/22697444/ba5df21e-ed51-11e6-8e0c-858dfe9172b1.png)

**Other Colorscheme** 
![image](https://cloud.githubusercontent.com/assets/3010752/22697526/f6286c2a-ed51-11e6-9dde-4af4e7160d07.png)

Maybe we change the background of the menu.

**Comment by rakr** [comment]
Here is how it looks like now

*dark*
<img width="457" alt="__w_vim-colorschemes" src="https://cloud.githubusercontent.com/assets/110558/22721866/4dba41b0-ee07-11e6-90f9-6a687356b6af.png">

*light*

<img width="457" alt="__w_vim-colorschemes" src="https://cloud.githubusercontent.com/assets/110558/22721888/73637d8c-ee07-11e6-980c-9039f17cf6f8.png">

**Comment by DenniJensen** [comment]
@rakr thx, looks good
