### ISSUE TITLE
gVim E254: Cannot allocate color #none 

### ISSUE THREAD

**Issue by konradx** [rakr/vim-one#34]
Hi,
I'm getting following errors with gVim on Linux

**Error detected while processing function <SNR>23_X: line   25: 
E254: Cannot allocate color #none**

After some investigation I found that changing following lines from
`call <sid>X('MatchParen',   s:hue_5,         'none',           'underline')`
`call <sid>X('MatchTag',   s:hue_5,         'none',           'underline')`
to

`call <sid>X('MatchParen',   s:hue_5,         '',           'underline')`
`call <sid>X('MatchTag',   s:hue_5,         '',           `'underline')`

fixes errors but gives me ugly background color.
To temporarily fix that I've put following in my .vimrc
`hi MatchParen guibg=NONE`

I believe initial error is caused by vim receiving **#none** instead of **none** as guibg argument.

**Comment by IngoHeimbach** [comment]
Same here in terminal vim :(

**Comment by rakr** [comment]
Hi guys,
Thanks for spotting this, this does not happen with Neovim.
I just pushed a quick fix to address this issue.
The idea is to make the MatchParen hightlight a little more subtle than it is, just bold red with underline and no specific background.

**Comment by konradx** [comment]
Works for me, thanks @rakr
