### ISSUE TITLE
constants in C are formatted like strings

### ISSUE THREAD

**Issue by rumpelsepp** [rakr/vim-one#36]
"keywords" like `NULL`, `stderr`, ... in C are formatted like strings. This is a bit confusing.

![screenshot from 2017-02-22 10-00-36](https://cloud.githubusercontent.com/assets/1961699/23204176/c6f40078-f8e5-11e6-9931-275411edb52b.png)

In atom it looks like this:

![screenshot from 2017-02-22 10-02-13](https://cloud.githubusercontent.com/assets/1961699/23204222/fff37354-f8e5-11e6-9d94-fa44572895ab.png)

Do you mind chaning it?

----

I also saw, that atom treats struct members differently. Stuff like this:

```C
s->bla = 5;
```

atom
![screenshot from 2017-02-22 10-04-09](https://cloud.githubusercontent.com/assets/1961699/23204308/56bc4ef4-f8e6-11e6-8687-5c3debc9ac65.png)

vim

![screenshot from 2017-02-22 10-04-31](https://cloud.githubusercontent.com/assets/1961699/23204318/5c1570ec-f8e6-11e6-991a-02bcd201280e.png)

---

edit: look at the first screenshot. There are even more differences. e.g. the datetypes do not match.

**Comment by rakr** [comment]
Hi, I made some progress on this one. One provides colors for the different grammars that are implemented. Vim default C/C++ highlight definition is quite minimal, I found this package that enhances the support for these languages: octol/vim-cpp-enhanced-highlight

Give it a shot and let me know if that fixes the issue.
