### ISSUE TITLE
terminal colors are missing

### ISSUE THREAD

**Issue by rumpelsepp** [rakr/vim-one#37]
We need sth. like this in this theme for neovim users:

https://github.com/joshdick/onedark.vim/blob/master/colors/onedark.vim#L471-L494

terminal buffers tend to look ugly without this.

**Comment by rakr** [comment]
I might use what is done for two-firewatch as a first iteration, need to work on this.

**Comment by rakr** [comment]
It's been hectic lately, and I'm trying to close as many issues as possible.
I just pushed a new version that addresses this issue, please have a look when you have some time.
