### ISSUE TITLE
Curly brackets viml

### ISSUE THREAD

**Issue by rumpelsepp** [rakr/vim-one#40]
In viml curly brackets are gray. IMO it should be an other color.

![screenshot from 2017-03-01 18-02-25](https://cloud.githubusercontent.com/assets/1961699/23471341/4a3cc78a-fea9-11e6-9247-9bae9c52af65.png)

**Comment by rumpelsepp** [comment]
same with css

![screenshot from 2017-03-01 23-14-09](https://cloud.githubusercontent.com/assets/1961699/23483839/d205e734-fed4-11e6-931e-4f099d859328.png)

**Comment by rakr** [comment]
Just pushed an update that takes care of this, whilst keeping the curly braces subtle enough (I don't like when they scream at me :) )
Please have a look and tell me what you think.

**Comment by rumpelsepp** [comment]
Thank you! Yeah, that looks better!

![screenshot from 2017-03-03 21-35-44](https://cloud.githubusercontent.com/assets/1961699/23568089/608e85f8-0059-11e7-985a-da9e859588ec.png)
