### ISSUE TITLE
Override defaults without forking

### ISSUE THREAD

**Issue by petobens** [rakr/vim-one#41]
Hi, is there a way to override default hl groups without forking the repo?. I'm looking for something similar to: https://github.com/joshdick/onedark.vim#customizing-onedarkvims-look-without-forking-the-repository.

Also: what's the difference between this colorscheme and https://github.com/joshdick/onedark.vim? 

Thanks in advance

**Comment by rakr** [comment]
Hi Pedro,

This is a nice idea, I'll dig into this.

I've been asked the question several times, or at least different flavours of it, below some answers:

- One has a light **and** dark version, Josh's implementation is only dark
- No differences outside of the above, as this is the adaptation of an Atom Theme, so trying to be as close to the original as possible.
- I wanted to experience open source in the wild with my own pet project, this is a modest contribution, but it is mine :)

**Comment by petobens** [comment]
Hi @rakr thanks for the detailed explanation.
Ok in the meantime i''ll will fork the repo. Nice work!!

**Comment by rakr** [comment]
Thanks, really appreciated.
Stay tuned this feature may come relatively fast...
Keeping your issue to track the progress on this one.

**Comment by rakr** [comment]
Well, I said relatively fast, I wasn't lying, even though it's been more than a month, here it is now.

you can use the following publicly exposed function to tweak one to suit your needs without having to fork it:

```
call one#highlight(group, fg, bg, attribute)
```

You can have a look at this, let me know what you think.

**Comment by petobens** [comment]
Awesome. Thank you! Fell free to close.
