### ISSUE TITLE
Improve C/C++ color scheme

### ISSUE THREAD

**Issue by jetm** [rakr/vim-one#42]
Look in the image, C/C++ comments are shown brighter than onedark does. In my opinion (no an expert on colors schemes), comments should be more obscure, like onedark is showing. (vim one at the left, onedark at the right)

![](https://cloud.githubusercontent.com/assets/474838/24778459/ed2b7f90-1ae7-11e7-80c2-8a55c23fa9a3.png)

Also there are color difference in C language keywords, like **if** and **return**. I think they should have the same color. These are all the C keywords: http://en.cppreference.com/w/c/keyword

**Comment by jetm** [comment]
@rakr: I tested with severals C and C++ files and they look good. Thanks!

In my initial issue post, a just put just the C keywords. These are C++ keywords: http://en.cppreference.com/w/cpp/keyword. Are they considered as well?

**Comment by rakr** [comment]
Hi @jetm, yes I think we could consider them, bear in mind that by default these keywords are linked with C keywords.
I like to use this command before making any change to see if the links do make sense (Including my mapping in `init.vim`)


```
" Display highlighting groups
nnoremap <leader>hi :so $VIMRUNTIME/syntax/hitest.vim<cr>
```
