### ISSUE TITLE
Showing confusing matching

### ISSUE THREAD

**Issue by taq** [rakr/vim-one#47]
I'm facing an weird situation here. If I use the colorscheme, and have some code like
```
if (var == 1) {
}
```
When I'm on the first `(`, it shows `)` using bold, with black over red. When I'm on `{`, it shows the `}` using bold, with black over red. So it makes me feels that I'm on the end char when I'm on the start! Don't know if there are some configuration for that, but on other themes it works ok.

**Comment by rakr** [comment]
Does this look like what you are experiencing?
<img width="272" alt="1__accueil__nvim_test_c__nvim_" src="https://cloud.githubusercontent.com/assets/110558/25728928/6240445c-3175-11e7-9ff0-3e18cbf882e0.png">
<img width="302" alt="1__accueil__nvim_test_c__nvim_" src="https://cloud.githubusercontent.com/assets/110558/25728964/8dd2d0d0-3175-11e7-9bae-1e828a4a91c1.png">

with a dark background:

<img width="272" alt="1__accueil__nvim_test_c__nvim_" src="https://cloud.githubusercontent.com/assets/110558/25728983/b2113888-3175-11e7-8e65-8685e196aea6.png">
<img width="272" alt="1__accueil__nvim_test_c__nvim_" src="https://cloud.githubusercontent.com/assets/110558/25728987/bc29c2ea-3175-11e7-96d4-7bddd7e33961.png">

**Comment by taq** [comment]
Yeah! As I'm using the dark background, the cursor on the match is black with a red background, so it looks like it's the cursor there. On your first dark example, under the cursor it will be no difference but on the match it will be a black `)` char over a red background. 

![one](https://cloud.githubusercontent.com/assets/9789/25742557/5e68ab76-3166-11e7-9f38-be66eddee2cb.png)

**Comment by taq** [comment]
Forgot to say, this behavior is just on the `one` theme, the `onedark` works ok.

**Comment by rakr** [comment]
can you try the following command and let me know if something changes:

```
:call one#highlight('MatchParen', 'e06c75', '', '')
```

Also, if you can provide more information on your setup:
- OS
- Terminal
- Vim or Neovim version

**Comment by taq** [comment]
Just got a E117: function unknown. But the code is there:

```
colors/one.vim:  function! one#highlight(group, fg, bg, attr)
```
- Ubuntu 17.04
- Gnome Terminal
- Neovim v0.2.1-dev

**Comment by rakr** [comment]
Oh, it seems that you are running an old version, do you mind updating the colorscheme

**Comment by taq** [comment]
Weird, the last commit on the repo (I installed it using Vundle) seems updated:

```
commit 2fe00fc767f001984755886d6edf056029f1d946
Merge: 9b5defa 14d7b12
Author: Ramzi Akremi <ramzi.dev@icloud.com>
Date:   Thu May 4 18:19:45 2017 +1000

    Merge pull request #46 from nguquen/master
    
    Define color for Neovim 0.2.0: `Whitespace` highlight group
```
Just run `:PluginUpdate` now and no changes found. :-(

**Comment by taq** [comment]
I'll remove it and install it again.

**Comment by taq** [comment]
Jesus Mary Joseph. Just found a pre-plugin version of `one` on my `colors` directory! :-p

**Comment by rakr** [comment]
Thanks, I was going to curse as well!

**Comment by taq** [comment]
Dude, shame on me! Sorry! It was the old version. :-( Now is working ok!
