### ISSUE TITLE
reloading init.vim swaps colors

### ISSUE THREAD

**Issue by adamki** [rakr/vim-one#51]
I have noticed that the colors rendered can change after the event of a reloading `.config/nvim/init.vim`. 

Here, I am using the following lines in my `init.vim` file:

```
  call dein#add('rakr/vim-one')

  syntax on
  colorscheme one
  set background=dark
  let g:one_allow_italics = 1

  let g:airline_theme='one'
```

I am using neovim and iTerm 2. True colors has been set via `set termguicolors` in neovim config.

I've included a screen share of the issue. Please let me know if more info is needed:
![may-30-2017 15-52-24](https://cloud.githubusercontent.com/assets/10334352/26608353/09a9be42-4550-11e7-80d3-4a29d082fb40.gif)

**Comment by rakr** [comment]
Hi Adam,

If you swap your `background` and `colorscheme` lines this should solve your problem,
```
call dein#add('rakr/vim-one')

  syntax on
  set background=dark
  colorscheme one
  let g:one_allow_italics = 1

  let g:airline_theme='one'
```

This is a known issue with Vim.

**Comment by adamki** [comment]
Most excellent! Thanks @rakr. things are looking great.
