### ISSUE TITLE
Color weirdness.

### ISSUE THREAD

**Issue by yakschuss** [rakr/vim-one#54]
Any idea why the dark theme doesn't fill in all the colors? The light theme works well.
![screen shot 2017-06-18 at 4 09 30 pm](https://user-images.githubusercontent.com/14119092/27263865-c0348558-5440-11e7-90d6-b203cd894200.png)
![screen shot 2017-06-18 at 4 11 22 pm](https://user-images.githubusercontent.com/14119092/27263868-ccc4e1a0-5440-11e7-9d00-97e1b721d7ce.png)

**Comment by rakr** [comment]
Hi Jack,

Not able to elaborate that much without more details, the only reason that I can see for the moment is that you are setting the background before changing the colorscheme.
You can have a look at the following issues where people did encounter the same problem.

#49, #50, #51 

Let me know if that works

**Comment by yakschuss** [comment]
Thanks :)
