### ISSUE TITLE
*-256color and gvim support

### ISSUE THREAD

**Issue by dylnmc** [rakr/vim-one#56]
support gvim (easy -- how could this not be supported?)

support *-256color `TERM`s (harder because you have to configure palette)

**Comment by rakr** [comment]
I tried on macvim, the colorscheme is supported and displays true colours. I'm not testing the colorscheme on all combinations of vim/OS (my dev environment is iTerm2/Neovim).
For 256color `TERM` the colorscheme uses approximation to adjust the colors which is a strategy that is probably not perfect but can be efficient.
One works best when true colour is supported.

**Comment by dylnmc** [comment]
no problem. sorry for issue. I have adapted another colorshceme to my liking.
