### ISSUE TITLE
doesnt show completion popup with terminal

### ISSUE THREAD

**Issue by kobayashi** [rakr/vim-one#68]
Completion popup is bkack-out while using terminal.

<img width="209" alt="screen shot 2017-11-01 at 10 13 31 pm" src="https://user-images.githubusercontent.com/8712070/32306518-40f1d444-bf52-11e7-9f19-01e3d299a138.png">

It is with macvim.

<img width="262" alt="screen shot 2017-11-01 at 10 14 20 pm" src="https://user-images.githubusercontent.com/8712070/32306510-384e0d94-bf52-11e7-8759-9015c7f5fc49.png">

My color settings in vmrc are the followings.
```
syntax on
hi Comment cterm=italic
set t_Co=256
set background=dark
colorscheme one
```

**Comment by rakr** [comment]
This is probably because you are using 256 colors, try to replace `set t_Co=256` with `set termguicolors`

**Comment by kobayashi** [comment]
Thanks @rakr 
Solved!!
