### ISSUE TITLE
Add support for Python

### ISSUE THREAD

**Issue by rakr** [rakr/vim-one#7]

**Comment by kepbod** [comment]
Could it also support [Cython](http://cython.org). Thanks!

**Comment by lohmander** [comment]
Any progress on this?

**Comment by rakr** [comment]
Hi @lohmander, sorry to report that I made no progress on this.
I'm not familiar with Python, I've never used it actually so the motivation is lacking a little bit here.
Also, like for Rust or other languages, PR are welcome.

I'm going to have long flight very soon, so this will be an opportunity to work on this :)

**Comment by rakr** [comment]
Hi,

Gave a stab at this issue, I had a good surprise so far, it seems that without any modification the python support is not that bad.
See below a side by side comparison between vim (on the left) and atom (on the right).

<img width="1128" alt="util_py_ ___workspaces_config_nvim_plugged_deoplete_nvim_rplugin_python3_deoplete_and_util_py____workspaces_config_nvim_plugged_deoplete_nvim_rplugin_python3_deoplete__-_nvim" src="https://cloud.githubusercontent.com/assets/110558/22187774/60599eb4-e160-11e6-8f10-d987e6bfe424.png">

**Comment by lohmander** [comment]
@rakr Hi! Sorry for my inactivity. It does indeed look pretty good already! Seems like it'd only require some minor tweaks to take it to 100%. Unfortunately I won't have time to look at this for a couple of weeks (gonna be traveling). But might be able to take a look once I'm back.
