### ISSUE TITLE
Undefined variable error in iTerm2

### ISSUE THREAD

**Issue by jonsmithers** [rakr/vim-one#77]
I'm getting this error when switching to the colorscheme:

```
Error detected while processing /Users/smithers/.vim/plugged/vim-one/colors/one.vim:
line  840:
E121: Undefined variable: s:dark
E15: Invalid expression: s:dark
Press ENTER or type command to continue
```

Here is a minimal vimrc I've been using to test this:

```vim
set runtimepath^=~/.vim/plugged/vim-one/
syntax enable        " error occurs with or without this
set termguicolors    " error occurs with or without this
set background=light " error occurs with or without this
colorscheme one
```

It doesn't happen in Terminal, only iTerm. I tried creating a brand new iTerm profile so everything was default but the error persists.

**Comment by jonsmithers** [comment]
`s:dark` only gets declared if one of these conditions is met:

```vim
if has('gui_running') || &t_Co == 88 || &t_Co == 256
```
For me, `&t_Co` is `8`. And I'm running inside a terminal.

**Comment by jonsmithers** [comment]
Adding `set t_Co=256` in the minimal vimrc gets it to work. 

This is traditionally how I get all my colors:

```vim
     if (has('termguicolors'))
       set termguicolors
     else
       set t_Co=256
     endif
```

**Comment by sseale** [comment]
I get this with Mac Terminal as well

colorscheme one
let g:one_allow_italics = 1
set background=dark

Error detected while processing /Users/sseale/.vim/plugged/vim-one/colors/one.vim:
line  840:
E121: Undefined variable: s:dark
E15: Invalid expression: s:dark
E121: Undefined variable: s:dark
E15: Invalid expression: s:dark
E121: Undefined variable: s:dark
E15: Invalid expression: s:dark

**Comment by tlemens** [comment]
Same here with Mate Terminal 1.18.2
@jonsmithers solution works for me
