### ISSUE TITLE
can you tell me the font name ? thanks you :)

### ISSUE THREAD

**Issue by hufeng** [rakr/vim-one#8]
https://github.com/rakr/vim-one/blob/master/screenshots/one.png

**Comment by rakr** [comment]
The font is [PragmataPro](http://www.fsd.it/shop/fonts/pragmatapro/).
It's a commercial font

**Comment by kaspergrubbe** [comment]
@rakr Do you mind sharing your font settings? Are you using iTerm? And what font size?
