### ISSUE TITLE
Cursorline background not currect in tmux

### ISSUE THREAD

**Issue by lisiyuan656** [rakr/vim-one#89]
I'm using the default onedark theme in SpaceVim. I found the background color for the cursorline is not correct when I run vim in tmux.
![screen shot 2019-01-18 at 3 24 35 pm](https://user-images.githubusercontent.com/7189111/51372983-e0327600-1b39-11e9-84ac-fa6f960b84c9.png)

But it's working correctly when I run vim directly in iterm2
![screen shot 2019-01-18 at 3 29 39 pm](https://user-images.githubusercontent.com/7189111/51373018-f6d8cd00-1b39-11e9-8ba1-24b07790c211.png)

Can anyone help me? Thank you guys so much!

**Comment by disrupted** [comment]
@lisiyuan656 did you figure it out yourself? I am with the exact same issue and just spent an hour going through every possible configuration I could imagine. the background color still comes up differently when run inside tmux.

**Comment by lisiyuan656** [comment]
Yeah, it's working for me now. But I'm not quite sure what the problem is... I'm using SpaceVim and I just updated all the plugins I installed. I also use this tmux plugin "odedlaz/tmux-onedark-theme". Maybe try to update the plugins and Install the tmux plugin. Hope that can help you.
