### ISSUE TITLE
Syntax Colors Don't Display

### ISSUE THREAD

**Issue by joshloftis** [rakr/vim-one#92]
I might have a config wrong somewhere. When using `vim-one` colorscheme the syntax highlighting doesn't seem to work on any file type. For example, Javascript and Elixir below:

<img width="813" alt="screen shot 2019-02-18 at 12 53 45 pm" src="https://user-images.githubusercontent.com/27499998/52969097-28cd9100-337d-11e9-98da-5ef7a4c47ef4.png">

<img width="813" alt="screen shot 2019-02-18 at 12 53 59 pm" src="https://user-images.githubusercontent.com/27499998/52969102-2cf9ae80-337d-11e9-90db-362000b9dfe2.png">

vim.rc:
```
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'rakr/vim-one'
call vundle#end()
filetype plugin indent on

set termguicolors
colorscheme one
syntax on
set background=dark
colorscheme one
```

Using Vim version 8.1 with macVim on macOS Mojave. 
Loading vim in iterm2 also looks the same as the pictures above - the syntax doesn't color correctly.
Checked my $TERM and it is xterm-256color

**Comment by joshloftis** [comment]
Realized I was missing language specific plugins.

**Comment by marroquinsamy** [comment]
Hi, I have the same issue with JavaScript. I have the coc-eslint installed. How did you solve it? Thanks for your time.
