### ISSUE TITLE
Add support for Lightline

### ISSUE THREAD

**Issue by lourenci** [rakr/vim-one#96]
Is there some plan to support lightline?

Thanks for the colorscheme.

**Comment by nwaywood** [comment]
@lourenci I use vim-one with lightline's built in [one theme](https://github.com/itchyny/lightline.vim#one) and it works perfectly for me

**Comment by lourenci** [comment]
Probably, they have added support for it. I'll close this issue since I'm not using Lightline anymore and this seems to be an issue just for me.

Thanks.
